### ISSUE TITLE
A marketing pitch for the landing page

### ISSUE THREAD

**Issue by kesh92** [kesh92/Project_51#5]
We need a good about section that pulls visitors, while also staying true to the vision and explaining the idea and capabilities in a clear, precise way. 

Things required:
* What is AVBOX?
* How it works? (as the name suggests)

**Comment by zaynalam** [comment]
1)TAGLINE TYPE: - The world is always moving. It's time to lead the movement.
- The digital revolution is here. Where do you plan to be?
- Hear the world. See the world. Create the world.
- Share what you love. Share what you create. Show who you are.
- The world around you is getting smaller. Your opportunities are getting larger.
- Opening doors to all realms in the digital world.
- Your entire online creative presence, all at one stop.

**Comment by zaynalam** [comment]
What is Traxys
 Traxys is the new digital portfolio network for the artists, from the artists and by the artists.
As the world grows increasingly smaller by the day, it is easy to get lost in the crowd and even more difficult to stand out as an artist or original content creator with talent bursting all around you. Traxys is the social network of the modern age that allows you, to bring all your talent onto one single platform and display for all the world to see.

**Comment by zaynalam** [comment]
What is Traxys #2
We provide a completely free online tool to bring together artists and original content creators onto one digital platform.
With integration from various other social content websites, we provide you the the right elements to create, customize and share your very own online portfolio with like minded people.
What sets us apart from the crowd, is that we cater only to the creators, the artists and the architects of entertainment in this century of the digital revolution. We want to develop a community for artists to network, share their work, gain recognition and find the right opportunities for their various talents and skills to be showcased and used.

**Comment by zaynalam** [comment]
How it works #1
Sign up, create a profile.
Link your traxys profile to the other social networking sites you wish to display on your traxys dashfolio.
Customize your Dashfolio with the things that make you, you.
Start following interests, connecting with like minded traxys users and start networking!
Its as simple as that

**Comment by kesh92** [comment]
I loved the first 'About' idea for the website. I do suggest  that once everything is done, we upload a video as well to show people how it works. 

'Your entire online creative presence, all at one stop.' Nailed it
