### ISSUE TITLE
Password popup for unacceptable inputs

### ISSUE THREAD

**Issue by kesh92** [kesh92/Project_51#8]
The password form should only accept inputs of the following types: 
1. >= 8 characters
2. alphanumeric
3. Atleast one number

Therefore, a popup should appear that informs of an illegal input. 

Let me know if the password criterion work @zaynalam

**Comment by zaynalam** [comment]
Criterion are fine.
http://www.the-art-of-web.com/javascript/validate-password/

It can be done with javascript.  modify and Add this to the landing page with the criterion that we reuire.
